# Generated by Django 3.2.12 on 2022-03-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0004_auto_20220305_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='care_sub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='treatments.caresubtype'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='care_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='treatments.caretype'),
        ),
    ]
