# Generated by Django 3.2.12 on 2022-03-04 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treatments', '0005_auto_20220305_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='care_sub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='treatments.caresubtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='care_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='treatments.caretype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='given_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
