# Generated by Django 3.2.12 on 2022-03-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0010_alter_patientdisease_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdisease',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
