# Generated by Django 3.2.12 on 2022-03-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0011_patientdisease_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
