# Generated by Django 3.2.12 on 2022-03-05 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
        ('treatments', '0012_treatment_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentnote',
            name='visit_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visits.visitdetail'),
            preserve_default=False,
        ),
    ]
