# Generated by Django 3.2.12 on 2022-03-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0013_treatmentnote_visit_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentnote',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
