# Generated by Django 3.2.12 on 2022-03-02 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0006_auto_20220224_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('birth_date', models.DateField(null=True)),
                ('phone_number', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=200)),
                ('landmark', models.CharField(max_length=200)),
                ('emergency_phone_number', models.CharField(max_length=14, null=True)),
                ('expired_time', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.ward')),
            ],
        ),
    ]
