# Generated by Django 3.2.12 on 2022-03-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='mail@abc.com', max_length=254),
            preserve_default=False,
        ),
    ]
