# Generated by Django 3.2.12 on 2022-03-03 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='updated_on',
            new_name='updated_at',
        ),
        migrations.CreateModel(
            name='PatientFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField(null=True)),
                ('phone_number', models.CharField(max_length=14)),
                ('relation', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
