# Generated by Django 3.2.12 on 2022-03-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20220303_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfamily',
            name='relation',
            field=models.CharField(choices=[('1', 'Father')], default='1', max_length=50),
        ),
    ]
