# Generated by Django 3.2.12 on 2022-02-23 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='lsg_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lsgbody'),
        ),
        migrations.DeleteModel(
            name='LsgBody',
        ),
    ]
