# Generated by Django 3.2.12 on 2022-02-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_facility_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='facility',
            name='pin_code',
            field=models.CharField(max_length=6),
        ),
    ]
