# Generated by Django 3.2.12 on 2022-02-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_auto_20220223_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='kind',
            field=models.CharField(choices=[('phc', 'PHC'), ('chc', 'CHC')], default='phc', max_length=100),
        ),
    ]
