# Generated by Django 3.2.12 on 2022-02-24 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_alter_facility_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facility',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
